### ISSUE TITLE
Input is not proper UTF-8, indicate encoding !

### ISSUE THREAD

**Issue by XMegamanX** [MediaArea/MediaConch_SourceCode#658]
Hello !

I have a problem with using Mediaconch and a source file. In this file, in the video track, there is a title 'Module de gestion vidéo'. MediaInfo ignores this element but Mediaconch failes with this particular error message : 'Validation generated an internal error:	Entity: line 98: 	parser 	error : 	Input is not proper UTF-8, indicate encoding !
Bytes: 0x8E 0x6F 0x3C 0x2F
	"Component flags mask">0</d><d o="5932" n="Component name">Module de gestion vid'

I use MediaConch Command Line Interface 18.03.2 and MediaInfo Command line, MediaInfoLib - v18.03.1.

Thank you :)

**Comment by JeromeMartinez** [comment]
I think this is fixed in a snapshot, please try the latest snapshot at https://mediaarea.net/download/snapshots/binary/mediaconch-gui/ (clear the database after install of the new version).

**Comment by XMegamanX** [comment]
Alright, thank you. I will give it a try. How can I clear the database ?

Regards

**Comment by JeromeMartinez** [comment]
with command line: use " --force" flag on the command line when you parse again the file.
I missed that you use the command line, so snapshots of command line are at https://mediaarea.net/download/snapshots/binary/mediaconch/

**Comment by EtienneChampion** [comment]
Hello @JeromeMartinez 
I work with @XMegamanX, we have tested the last snapshot (18.03.2.20190705) but we still get this error when parsing some files. 
We use this command : 
`mediaconch --force --ParseSpeed=0.5 --Policy=MPEG-4.xml --Format=XML "file.mp4"`

And the output is :
`Validation generated an internal error:	Entity: line 103: 	parser 	error : 	Input is not proper UTF-8, indicate encoding !
Bytes: 0x8E 0x6F 0x3C 0x2F
	ponent flags mask">0</d><d o="12890174" n="Component name">Module de gestion vid
	                                                                               ^`

Can you help us ?
Thank you

**Comment by JeromeMartinez** [comment]
Fixed in https://github.com/MediaArea/MediaInfoLib/pull/1168, development build available in our [snapshots](https://mediaarea.net/download/snapshots/binary/).
